var tipack=tipack||{};
tipack.App=tipack.App||function(d){return function(d){var b=d.project,a=d.callback||function(){},c={},e=new tipack.Hub,j=!1;c.run=function(){if(!j){var e={project:b,baseDir:tipack.Filesystem.getAppDir(b.archiveId).resolve()};a({type:"app_setup",params:e});var i=Ti.UI.createWindow({url:"/tipack/AppWrapper.js"});i.params=e;"android"!==Ti.Platform.getOsname()&&i.add(Ti.UI.createImageView(tipack.Utils.getDefaultIosImageParams()));a({type:"app_run",win:i});j=!0;i.addEventListener("exit",function(b){a({type:"app_close",
win:i});j=!1;i.close();c.fireEvent("close",{reason:b.reason?b.reason:"unknown"})});i.addEventListener("safe",function(a){c.fireEvent("safe",a)});i.open()}};c.addEventListener=function(a,c){e.addEventListener(a,c)};c.removeEventListener=function(a,c){e.removeEventListener(a,c)};c.fireEvent=function(a,c){e.fireEvent(a,c)};c.isRunning=function(){return j};return c}(d)};tipack=tipack||{};
tipack.Downloader=tipack.Downloader||function(){return{download:function(d){var f=d.url,b=d.file,a=d.callback||function(){},c=d.progressCallback||function(){},e=Ti.Network.createHTTPClient({ondatastream:function(a){c(a.progress)},onload:function(){var c=this.responseText;null!==c?b.write(c)?a({params:d}):a({params:d,error:{code:"io",message:"could not write file"}}):a({params:d,error:{code:"io",message:"invalid file format (not text)"}})},onerror:function(){a({params:d,error:{code:"io",message:"could not download file"}})},
timeout:d.timeout||6E4});e.open("GET",f);e.setRequestHeader("User-Agent",tipack.getDefaultUserAgent());e.setRequestHeader("Range","bytes=0-");e.send()}}}();tipack=tipack||{};
tipack.Filesystem=tipack.Filesystem||function(){function d(){var a;"android"===Ti.Platform.getOsname()?a=Ti.Filesystem.getApplicationDataDirectory():(a=Ti.Filesystem.getFile(Ti.Filesystem.getApplicationDataDirectory()).nativePath,"/"!==a.charAt(a.length-1)&&(a+="/"),a=a.replace("Documents/",""),a+="Library/Private%20Documents/");return a}function f(a,c){var c=c||[],b=a.getDirectoryListing();if(b)for(var d=0,h=b.length;d<h;++d){for(var i=b[d],g=!1,f=0,k=c.length;f<k;++f)if(i===c[f]){g=!0;break}g||
(i=Ti.Filesystem.getFile(a.nativePath,i),g=i,g.isDirectory?g=g.isDirectory():g.exists()?(g=g.nativePath,g=g[g.length-1]===Ti.Filesystem.getSeparator()):g=!1,g?i.deleteDirectory(!0):i.deleteFile())}}var b={getArchivesDir:function(){return Ti.Filesystem.getFile(d(),"tipack","archives")},getArchiveFile:function(a){return Ti.Filesystem.getFile(d(),"tipack","archives",a+".json")},getAppsDir:function(){return Ti.Filesystem.getFile(d(),"tipack","apps")},getAppDir:function(a){return Ti.Filesystem.getFile(d(),
"tipack","apps",a)},getAppFlagFile:function(a){return Ti.Filesystem.getFile(d(),"tipack","apps",a+".flag")},createDirectoryStructure:function(){var a=Ti.Filesystem.getFile(d());a.createDirectory();a=Ti.Filesystem.getFile(d(),"tipack");a.createDirectory();a.setRemoteBackup&&a.setRemoteBackup(!1);a=Ti.Filesystem.getFile(d(),"tipack","archives");a.createDirectory();a=Ti.Filesystem.getFile(d(),"tipack","apps");a.createDirectory()},cleanup:function(a){var a=a||{},a=a.excludeArchiveId||null,c=null!==a?
a+".json":null;f(b.getArchivesDir(),[c]);c=null!==a?a+".flag":null;a=null!==a?a:null;f(b.getAppsDir(),[c,a])}};return b}();tipack=tipack||{};tipack.Hub=tipack.Hub||function(){return function(){var d={},f={};d.addEventListener=function(b,a){var c=f[b];"undefined"===typeof c&&(c=[],f[b]=c);c.push(a)};d.removeEventListener=function(b,a){var c=f[b];if("undefined"!==typeof c){var e=c.indexOf(a);-1!==e&&c.splice(e,1);0==c.length&&delete f[b]}};d.fireEvent=function(b,a){var c=f[b];if("undefined"!==typeof c)for(var e=0,d=c.length;e<d;++e)c[e](a)};d.getNumListeners=function(){var b=0,a;for(a in f)b+=f[a].length;return b};return d}()};tipack=tipack||{};
tipack.Loader=tipack.Loader||function(){function d(b){var a=b.projectId,c=b.useLatest,e=b.callback,b=tipack.Properties.getProject(a),j=!0;!c&&null!==b&&"undefined"!==typeof b.archiveId&&tipack.Filesystem.getArchiveFile(b.archiveId).exists()&&(j=!1);j?(e({type:"download_start"}),tipack.Utils.downloadProject({projectId:a,progressCallback:function(a){e({type:"download_progress",progress:a})},callback:function(c){e({type:"download_end"});c.error?e({type:"error",error:c.error}):d({projectId:a,useLatest:!1,
callback:e})}})):(e({type:"extract_start"}),tipack.Utils.extractArchive(b.archiveId),e({type:"extract_end"}),c=new tipack.App({project:b,callback:e}),c.addEventListener("close",function(a){"restart"===a.reason?f.loadDefault({callback:e}):"exit"===a.reason&&"android"===Ti.Platform.getOsname()&&Ti.Android.currentActivity.finish()}),c.addEventListener("safe",function(){tipack.Properties.setNumFailedRuns(0)}),tipack.Properties.setNumFailedRuns(tipack.Properties.getNumFailedRuns()+1),c.run())}var f={loadDefault:function(b){var a=
b.defaultProjectId,c=b.defaultUseLatest||!1,e=b.defaultNumFailedRuns||0,f=b.defaultMaxFailedRuns||3,b=b.callback||function(){};tipack.Filesystem.createDirectoryStructure();var h=tipack.Properties.getProjectId();null===h&&(h=a,tipack.Properties.setProjectId(h));a=tipack.Properties.getUseLatest();null===a&&(a=c,tipack.Properties.setUseLatest(a));c=tipack.Properties.getNumFailedRuns();null===c&&(c=e,tipack.Properties.setNumFailedRuns(c));e=tipack.Properties.getMaxFailedRuns();null===e&&(e=f,tipack.Properties.setMaxFailedRuns(e));
c>=e&&(a=!0);d({projectId:h,useLatest:a,callback:b})}};return f}();tipack=tipack||{};
tipack.Properties=tipack.Properties||function(){function d(){var a="tipack|"+Ti.App.id+"|"+Ti.App.version;return Ti.App.Properties.hasProperty(a)&&(a=Ti.App.Properties.getString(a),a=JSON.parse(a))?a:{}}function f(a){a=d()[a];return"undefined"!==typeof a?a:null}function b(a,c){var b=d();b[a]=c;b=JSON.stringify(b);Ti.App.Properties.setString("tipack|"+Ti.App.id+"|"+Ti.App.version,b)}return{getNumFailedRuns:function(){return f("numFailedRuns")},setNumFailedRuns:function(a){b("numFailedRuns",a)},getMaxFailedRuns:function(){return f("maxFailedRuns")},
setMaxFailedRuns:function(a){b("maxFailedRuns",a)},getProjectId:function(){return f("project")},setProjectId:function(a){b("project",a)},getProject:function(a){return f("projects/"+a)},setProject:function(a,c){b("projects/"+a,c)},getUseLatest:function(){return f("useLatest")},setUseLatest:function(a){b("useLatest",a)}}}();tipack=tipack||{};
tipack.Service=tipack.Service||function(){function d(a){"undefined"===typeof a&&(a="");var c=a.split("."),a=parseInt(c[0]),b=parseInt(c[1]),c=parseInt(c[2]);return{major:isNaN(a)?0:a,minor:isNaN(b)?0:b,build:isNaN(c)?0:c}}function f(a,c){var b=d(a),e=d(c);return b.major>e.major?"future":b.major<e.major?"major":b.minor>e.minor?"future":b.minor<e.minor?"minor":b.build>e.build?"future":b.build<e.build?"build":"latest"}function b(a){var b=a.callback,d=a.progressCallback,h=tipack.Properties.getProjectId(),j=
tipack.Properties.getProject(h);e.request({request:{type:"get_project",projectId:h},callback:function(a){if(a.error)b(a);else{var e=f(j.version,a.value.version);"major"!==e&&"minor"!==e?b({value:{type:e}}):(c.fireEvent("downloadStart",{}),tipack.Utils.downloadProject({projectId:h,progressCallback:d,callback:function(a){a.error?b(a):b({value:{type:e}})}}))}}})}function a(){h=null;b({progressCallback:function(a){c.fireEvent("progress",a)},callback:function(b){b.error||tipack.Instance.markSafeRun();
c.fireEvent("update",b);h=setTimeout(a,j)}})}var c=new tipack.Hub,e=new tipack.Client,j,h=null;c.checkUpdateNow=function(){null!==h&&(clearTimeout(h),a())};c.start=function(b){b=b||{};j=b.timeout||36E5;b=tipack.Instance.getProject();tipack.Filesystem.cleanup({excludeArchiveId:null!==b?b.archiveId:null});a()};return c}();tipack=tipack||{};
tipack.Utils=tipack.Utils||function(){var d={},f=new tipack.Client;d.getDefaultIosImageParams=function(){return 320===Ti.Platform.displayCaps.platformWidth?480==Ti.Platform.displayCaps.platformHeight?{image:"Default.png",top:0,left:0,right:0,bottom:0}:{image:"Default-568h.png",top:0,left:0,right:0,bottom:0}:{image:"Default-Portrait.png",top:0,left:0,right:0,bottom:0}};d.downloadProject=function(b){var a=b.projectId,c=b.callback,e=b.progressCallback;f.request({request:{type:"get_project",projectId:a},
callback:function(b){if(b.error)c({error:b.error});else{var d=b.value||null;(b=d.archive||null)?(tipack.Properties.setProject(a,d),d=tipack.Filesystem.getArchiveFile(b.id),d.exists()?c({}):tipack.Downloader.download({url:b.url,file:d,timeout:6E5,progressCallback:e,callback:function(a){a.error?c({error:a.error}):c({})}})):c({error:{code:"not_found",message:"no archive defined for project "+a}})}}})};d.extractArchive=function(b){var a=tipack.Filesystem.getAppFlagFile(b);if(!a.exists()){tipack.Filesystem.createDirectoryStructure();
var c=tipack.Filesystem.getAppDir(b);if(c.exists()&&!c.deleteDirectory(!0))throw Error("Could not delete apps directory");if(!c.createDirectory())throw Error("Could not create app directory: "+b);try{var d=tipack.Filesystem.getArchiveFile(b);if(!d.exists())throw Error("Archive file does not exist: "+b);for(var f=d.read().text,h=JSON.parse(f).files,b=0,i=h.length;b<i;++b){var g=h[b],l=Ti.Filesystem.getFile(c.resolve(),g.path);if("undefined"===typeof g.data){if(!l.createDirectory())throw Error("Could not create directory: "+
l.resolve());}else{var d=void 0,k=g.encoding;if("undefined"===typeof k||"text"===k)d=g.data;else if("base64"===k)d=Ti.Utils.base64decode(g.data);else throw Error("Unknown encoding: "+k);l.write(d);if(!l.exists())throw Error("Could not write file: "+l.resolve());}}}catch(m){throw c.deleteDirectory(!0),m;}a.write("")}};return d}();
